"""add miraheze fields to users

Revision ID: 36369c50179e
Revises: acc2691a9780
Create Date: 2026-05-30 02:00:51.408725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36369c50179e'
down_revision: Union[str, Sequence[str], None] = 'acc2691a9780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('miraheze_username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('miraheze_verify_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_miraheze_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_miraheze_verified')
    op.drop_column('users', 'miraheze_verify_code')
    op.drop_column('users', 'miraheze_username')
    # ### end Alembic commands ###
