"""add platform and has_ratepage to sites

Revision ID: acc2691a9780
Revises: a66fcd2ebc6c
Create Date: 2026-05-28 16:30:40.440187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc2691a9780'
down_revision: Union[str, Sequence[str], None] = 'a66fcd2ebc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 安全删除索引：使用 IF EXISTS 避免在未创建索引的新数据库上报错
    op.execute("DROP INDEX IF EXISTS idx_pages_title_gin")
    op.execute("DROP INDEX IF EXISTS idx_pages_wikitext_gin")
    op.add_column('sites', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('sites', sa.Column('has_ratepage', sa.Boolean(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'has_ratepage')
    op.drop_column('sites', 'platform')
    op.create_index(op.f('idx_pages_wikitext_gin'), 'pages', [sa.literal_column("to_tsvector('simple'::regconfig, COALESCE(wikitext, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_pages_title_gin'), 'pages', [sa.literal_column("to_tsvector('simple'::regconfig, COALESCE(title, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
